name: 'Push to ACR'

on:
  push:
    branches: [main]
  pull_request:
    branches: [feature/ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run list
        run: echo ls

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Display dotnet version
        run: dotnet --version

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Display Nodejs version
        run: |
          node --version
          npm --version
