name: 020-manual-input-workflow

on:
  workflow_dispatch:
    # input the workflow accepts
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
      age:
        description: 'Person to greet age'
        default: '0'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: |
          echo "Hello ${{github.event.inputs.name}}, "
          echo "Your age is ${{github.event.inputs.age}}"
