name: 'Push to ACR'

on:
  push:
    branches: [main]
  pull_request:
    branches: [feature/ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run list
        run: echo ls

      # - name: Install .NET Core
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 8.0.x

      # - name: Run dotnet
      #   uses: dotnet --list-sdks
