
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:  # Will be triggered manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one line script
        run: echo Hello, World!

      - name: Run a multil-line script
        run: |
          echo Add other actions to build.
          echo test, and deploy your project.

      - name: List files and folders
        run: ls -a
